name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'
  
permissions:
      contents: read
      id-token: write
env:
  PROJECT_ID: project-06cede75-fb8e-4bfb-984
  PROJECT_NUMBER: 489414658403
  
jobs:
  # ── 1. Terraform ──────────────────────────────────────────────
  terraform-plan:
    name: Terraform_Plan
    runs-on: ubuntu-latest
    
    outputs:
     Changed_dir: ${{ steps.change-dir.outputs.changed_dirs }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/489414658403/locations/global/workloadIdentityPools/github/providers/terraform'
          service_account: 'sa-terraform@project-06cede75-fb8e-4bfb-984.iam.gserviceaccount.com'

      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            terraform/**
          files_ignore: |
            .github/**
            terraform/.github/**

      - name: Get changed terraform directories
        id: change-dir
        run: |
          CHANGED_DIRS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" \
            | tr ' ' '\n' \
            | awk -F/ '{print $1"/"$2}' \
            | sort -u \
            | tr '\n' ' ')

          echo "Changed directories: $CHANGED_DIRS"

          echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      # - id: change-dir
      #   name: Get changed directories
      #   run: |
      #     CHANGED_DIRS=$(git diff --name-only origin/main...HEAD \
      #      | grep '^terraform/' \
      #      | grep -v '^\.github/' \
      #      | cut -d'/' -f1,2 \
      #      | sort -u)

      #     echo "$CHANGED_DIRS"
      #     echo "$CHANGED_DIRS" >> $GITHUB_OUTPUT

      # - name: Create GCS state bucket (if not exists)
      #   run: |
      #     gsutil mb -p $PROJECT_ID -l $REGION gs://${PROJECT_ID}-tfstate || true

      - name: Terraform Init and Plan
        run: |
          FOLDER_LIST=$(echo "${{ steps.change-dir.outputs.changed_dirs }}" | tr ' ' '\n')
          echo "${FOLDER_LIST}"
          for dir in $FOLDER_LIST; do
            echo "${FOLDER_LIST}"
            echo "Processing $dir"
            cd $dir
            terraform init
            terraform plan -out=tfplan
          done  
  
  terraform-apply:
    name: Terraform_Apply
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    #this job run when pull request is from 'main'
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/489414658403/locations/global/workloadIdentityPools/github/providers/terraform'
          service_account: 'sa-terraform@project-06cede75-fb8e-4bfb-984.iam.gserviceaccount.com'

      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: |
          for dir in ${{ needs.terraform-plan.outputs.Changed_dir }}; do
            echo "Processing $dir"
            cd $dir
            terraform init
            terraform apply -auto-approve
          done
    


    
